// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHTjEPNz547hYsuPf7z__XvMxr2Roj4Ek',
    appId: '1:104749019946:web:7e99ee734740273dde2453',
    messagingSenderId: '104749019946',
    projectId: 'lostfound-bd01',
    authDomain: 'lostfound-bd01.firebaseapp.com',
    storageBucket: 'lostfound-bd01.firebasestorage.app',
    measurementId: 'G-8D88K78JYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUXWaIdDcYAQhj-7kwRKkzA3rJzy5Wh18',
    appId: '1:104749019946:android:21bbddea42d014d6de2453',
    messagingSenderId: '104749019946',
    projectId: 'lostfound-bd01',
    storageBucket: 'lostfound-bd01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB_RKilLcC5hSsKwGryt4wxLbTKDENU60',
    appId: '1:104749019946:ios:4152f44da9eaf2f5de2453',
    messagingSenderId: '104749019946',
    projectId: 'lostfound-bd01',
    storageBucket: 'lostfound-bd01.firebasestorage.app',
    iosBundleId: 'com.example.lostfoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB_RKilLcC5hSsKwGryt4wxLbTKDENU60',
    appId: '1:104749019946:ios:4152f44da9eaf2f5de2453',
    messagingSenderId: '104749019946',
    projectId: 'lostfound-bd01',
    storageBucket: 'lostfound-bd01.firebasestorage.app',
    iosBundleId: 'com.example.lostfoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHTjEPNz547hYsuPf7z__XvMxr2Roj4Ek',
    appId: '1:104749019946:web:743756ab6a3eb22bde2453',
    messagingSenderId: '104749019946',
    projectId: 'lostfound-bd01',
    authDomain: 'lostfound-bd01.firebaseapp.com',
    storageBucket: 'lostfound-bd01.firebasestorage.app',
    measurementId: 'G-4S02DD775B',
  );
}
